server:
  port: 8088

spring:
  application:
    name: springcloud-config-client

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
  endpoint:
    health:
      show-details: always