server:
  port: 8087

# 服务与服务之间相互调用一般都是根据这个name 。
spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig.git
          searchPaths: respo
#          username: 852026881@qq.com
#          password: lbl0168
          skip-ssl-validation: true
          default-label: master
